export const ACTIONS = {
    CHANGE_SUBJECT_NAME: "CHANGE_SUBJECT_NAME",
    CHANGE_SUBJECT_CODE: "CHANGE_SUBJECT_CODE",
    CHANGE_SUBJECT_BRANCH: "CHANGE_SUBJECT_BRANCH",
    CHANGE_SUBJECT_CREDITS: "CHANGE_SUBJECT_CREDITS",
    RESET_STATE: "RESET_STATE",
  };
  
  export const SUBJECT_FORM_IDS = {
    SUBJECT_NAME: "subjectName",
    SUBJECT_CODE: "subjectCode",
    SUBJECT_BRANCH: "subjectBranch",
    SUBJECT_CREDITS: "subjectCredits",
  };
  
  export const SUBJECT_ADDITION_SUCCESS_MESSAGE = "New Subject Added Succesfully";
  
  export const SUBJECT_ADDITION_FAILURE_MESSAGE = "Please fill all Details correctly";
  
  export const EventIDActionsType = new Map([
    [SUBJECT_FORM_IDS.SUBJECT_NAME, ACTIONS.CHANGE_SUBJECT_NAME],
    [SUBJECT_FORM_IDS.SUBJECT_CODE, ACTIONS.CHANGE_SUBJECT_CODE],
    [SUBJECT_FORM_IDS.SUBJECT_BRANCH, ACTIONS.CHANGE_SUBJECT_BRANCH],
    [SUBJECT_FORM_IDS.SUBJECT_CREDITS, ACTIONS.CHANGE_SUBJECT_CREDITS],
  ]);
  